/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as CopilotsImport } from './routes/copilots'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SessionSessionIdImport } from './routes/session/$sessionId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const CopilotsRoute = CopilotsImport.update({
  id: '/copilots',
  path: '/copilots',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionIdRoute = SessionSessionIdImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/copilots': {
      id: '/copilots'
      path: '/copilots'
      fullPath: '/copilots'
      preLoaderRoute: typeof CopilotsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copilots': typeof CopilotsRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copilots': typeof CopilotsRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copilots': typeof CopilotsRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/copilots' | '/settings' | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/copilots' | '/settings' | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/copilots'
    | '/settings'
    | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CopilotsRoute: typeof CopilotsRoute
  SettingsRoute: typeof SettingsRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CopilotsRoute: CopilotsRoute,
  SettingsRoute: SettingsRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/copilots",
        "/settings",
        "/session/$sessionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/copilots": {
      "filePath": "copilots.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/session/$sessionId": {
      "filePath": "session/$sessionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
